"""
tools/tool_forge.py
The Tool Forge — creates, saves, and live-registers new tools from natural language.

Workflow:
  1. Agent calls this tool with a name, description, and behavior spec
  2. Forge generates a valid BaseTool subclass using the LLM
  3. Saves the file to tools/generated/
  4. Dynamically imports and registers it into TOOL_REGISTRY — no restart needed
  5. On next boot, agent.py auto-discovers tools/generated/ and reloads them

Teaching example:
  name: "tell_story"
  description: "Tells a short story in Gizmo's voice when asked."
  behavior: "Generate a 3-paragraph original story. Use sensory detail. End with a twist."

That's it. Kaylee taught Gizmo to tell stories.
"""

import os
import re
import ast
import sys
import importlib
import importlib.util
from pathlib import Path

from tools.base_tool import BaseTool, ToolResult

# Where generated tools live
GENERATED_DIR = Path(__file__).parent / "generated"


def _sanitize_name(name: str) -> str:
    """Convert any string to a valid Python identifier."""
    name = re.sub(r"[^\w]", "_", name.strip().lower())
    name = re.sub(r"_+", "_", name).strip("_")
    if not name:
        name = "unnamed_tool"
    return name


def _class_name(tool_name: str) -> str:
    return "".join(word.capitalize() for word in tool_name.split("_")) + "Tool"


TEMPLATE = '''"""
tools/generated/{filename}
Auto-generated by Tool Forge.
"""

from tools.base_tool import BaseTool, ToolResult


class {class_name}(BaseTool):

    @property
    def name(self) -> str:
        return "{tool_name}"

    @property
    def description(self) -> str:
        return (
            "{description}"
        )

    async def run(self, session_id: str = "", **kwargs) -> ToolResult:
{run_body}
'''


def _indent(code: str, spaces: int = 8) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in code.splitlines())


def _build_run_body(behavior: str) -> str:
    """
    Build the run() body from a behavior spec.
    For LLM-backed tools, emits a call to the internal llm.generate().
    For simple tools, emits a direct return.
    """
    # Heuristic: if behavior mentions "generate", "llm", "respond", "write", "story" etc.
    # → wire to LLM. Otherwise → static/simple return.
    llm_keywords = {"generat", "llm", "respond", "write", "story", "tell", "explain",
                    "summar", "translat", "compos", "craft", "describ", "answer"}
    behavior_lower = behavior.lower()
    is_llm_tool = any(kw in behavior_lower for kw in llm_keywords)

    if is_llm_tool:
        escaped = behavior.replace('"', '\\"').replace("'", "\\'")
        body = f'''\
from core.llm import llm as _llm
        prompt = (
            "You are Gizmo. {escaped}\\n\\n"
            + "\\n".join(f"{{k}}: {{v}}" for k, v in kwargs.items() if v)
        )
        result = await _llm.generate([{{"role": "user", "content": prompt}}])
        return ToolResult(success=True, output=result)'''
    else:
        escaped = behavior.replace('"', '\\"')
        body = f'return ToolResult(success=True, output="{escaped}")'

    return _indent(body)


async def _generate_run_body_via_llm(
    llm,
    tool_name: str,
    description: str,
    behavior: str,
) -> str:
    """
    Ask the LLM to write the run() body for complex tools.
    Falls back to template if generation fails.
    """
    prompt = f"""Write ONLY the body of an async Python method called `run` for a tool called `{tool_name}`.

Tool description: {description}
Behavior spec: {behavior}

Rules:
- The method signature is: async def run(self, session_id: str = "", **kwargs) -> ToolResult
- Import anything you need INSIDE the function body
- ToolResult is already imported: from tools.base_tool import ToolResult
- Return ToolResult(success=True, output=<string>) on success
- Return ToolResult(success=False, output=<error string>) on failure
- For LLM calls, use: from core.llm import llm as _llm
- DO NOT include the def line — only the body, indented 8 spaces
- DO NOT include markdown fences
- Keep it under 30 lines"""

    try:
        result = await llm.generate([{"role": "user", "content": prompt}])
        # Strip any accidental def lines or fences
        result = re.sub(r"```[\w]*\n?", "", result)
        result = re.sub(r"async def run.*?:\n", "", result)
        return result.strip()
    except Exception:
        return _build_run_body(behavior)


def _validate_syntax(code: str, filename: str) -> tuple[bool, str]:
    try:
        ast.parse(code)
        return True, ""
    except SyntaxError as e:
        return False, f"Syntax error in {filename}: {e}"


def _register_tool(filepath: Path, tool_name: str) -> tuple[bool, str]:
    """Dynamically import the generated file and register into TOOL_REGISTRY."""
    try:
        spec = importlib.util.spec_from_file_location(
            f"tools.generated.{tool_name}", filepath
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules[f"tools.generated.{tool_name}"] = module
        spec.loader.exec_module(module)

        # Find the BaseTool subclass
        tool_class = None
        for attr_name in dir(module):
            obj = getattr(module, attr_name)
            if (
                isinstance(obj, type)
                and issubclass(obj, BaseTool)
                and obj is not BaseTool
            ):
                tool_class = obj
                break

        if not tool_class:
            return False, "No BaseTool subclass found in generated file."

        instance = tool_class()

        # Import and mutate the live registry
        from core import agent as agent_module
        agent_module.TOOL_REGISTRY[instance.name] = instance

        return True, instance.name

    except Exception as e:
        return False, str(e)


class ToolForgeTool(BaseTool):

    @property
    def name(self) -> str:
        return "tool_forge"

    @property
    def description(self) -> str:
        return (
            "Creates a brand-new tool from scratch and registers it live — no restart needed. "
            "Use when someone says 'teach you to do X', 'make a tool that...', "
            "'add a skill for...', or 'I want you to be able to...'. "
            "Args: "
            "  tool_name (str) — short snake_case identifier, e.g. 'tell_story'. "
            "  description (str) — what the tool does and when to invoke it (the LLM reads this). "
            "  behavior (str) — HOW the tool runs: what it generates, returns, or does. "
            "The tool is saved to disk and reloads automatically on next restart."
        )

    async def run(
        self,
        tool_name: str = "",
        description: str = "",
        behavior: str = "",
        session_id: str = "",
        **kwargs,
    ) -> ToolResult:

        if not tool_name or not description or not behavior:
            return ToolResult(
                success=False,
                output=(
                    "Tool Forge needs three things: tool_name, description, and behavior. "
                    "Example: tool_name='tell_story', "
                    "description='Tells an original short story when asked.', "
                    "behavior='Generate a 3-paragraph story with sensory detail and a twist ending.'"
                ),
            )

        # 1. Sanitize and prepare names
        safe_name = _sanitize_name(tool_name)
        cls_name = _class_name(safe_name)
        filename = f"{safe_name}.py"
        filepath = GENERATED_DIR / filename

        # 2. Check for collision with core tools
        try:
            from core import agent as agent_module
            if safe_name in agent_module.TOOL_REGISTRY and safe_name not in (
                "echo", "switch_host", "log_correction"
            ):
                return ToolResult(
                    success=False,
                    output=f"A tool named '{safe_name}' already exists. Pick a different name or ask to overwrite it.",
                )
        except Exception:
            pass

        # 3. Generate run() body
        try:
            from core.llm import llm as _llm
            run_body = await _generate_run_body_via_llm(
                _llm, safe_name, description, behavior
            )
        except Exception:
            run_body = _build_run_body(behavior)

        # Ensure indentation
        if run_body and not run_body.startswith(" " * 8):
            run_body = _indent(run_body)

        # 4. Render the full file
        escaped_desc = description.replace('"', '\\"').replace("'", "\\'")
        source = TEMPLATE.format(
            filename=filename,
            class_name=cls_name,
            tool_name=safe_name,
            description=escaped_desc,
            run_body=run_body,
        )

        # 5. Validate syntax
        valid, err = _validate_syntax(source, filename)
        if not valid:
            # Fall back to template run body
            run_body = _build_run_body(behavior)
            if not run_body.startswith(" " * 8):
                run_body = _indent(run_body)
            source = TEMPLATE.format(
                filename=filename,
                class_name=cls_name,
                tool_name=safe_name,
                description=escaped_desc,
                run_body=run_body,
            )
            valid, err = _validate_syntax(source, filename)
            if not valid:
                return ToolResult(success=False, output=f"Failed to generate valid Python: {err}")

        # 6. Write to disk
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        init = GENERATED_DIR / "__init__.py"
        if not init.exists():
            init.write_text("# Auto-generated tool package\n")
        filepath.write_text(source, encoding="utf-8")

        # 7. Register live
        ok, result = _register_tool(filepath, safe_name)
        if not ok:
            return ToolResult(
                success=False,
                output=f"Tool saved to {filepath} but live registration failed: {result}. It will load on next restart.",
            )

        return ToolResult(
            success=True,
            output=(
                f"Tool '{safe_name}' is live. "
                f"Saved to tools/generated/{filename}. "
                f"Registered in TOOL_REGISTRY. "
                f"I can now use it immediately — no restart needed. "
                f"It will reload automatically on next boot."
            ),
            data={
                "tool_name": safe_name,
                "class_name": cls_name,
                "filepath": str(filepath),
                "description": description,
            },
        )
